exports.USER_TYPE = {
    HR: "HR",
    WORKER: "WORKER",
    ADMIN: "ADMIN"
}

exports.CLOCK_TYPE = {
    LUNCH_START: "LUNCH_START",
    LUNCH_END: "LUNCH_END",
    WORK_START: "WORK_START",
    WORK_END: "WORK_END"
}